/*
 * CharacterPanel.java
 *
 * Created on 05 December 2008, 10:08
 */

package gui;

import characters.Character;
import frames.FramesCollection;
import game.GameInvariants;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author  Gil Costa
 */
public class ListPanel extends javax.swing.JPanel {
    
    public static final String ADD_NEW_NAME = "Write text";
    
    ArrayList<String> lst;
    
    
    /** Creates new form CharacterPanel */
    public ListPanel() {
        initComponents();
    }
    
    
    
    
    public void setList(ArrayList<String> lst, String description){
        if (lst != null) update();
        this.lst = lst;
        label.setText(description);
        updateFields();
    }
    
    public ArrayList<String> getList(){ return lst; }
    
    
    protected static String getName(String s){
        if (s==null) return null;
        return s.substring(s.indexOf(' ')+1);
    }
    
    
    public void update(){
        if (lst == null) return;
        ListModel model = nameList.getModel();
        lst.clear();
        for(int i=0; i<model.getSize()-1; i++){
            lst.add(getName((String)model.getElementAt(i)));
        }
    }
    
 
    public void updateFields(){
        int index = nameList.getSelectedIndex();
        nameList.removeAll();
        DefaultListModel listModel = new DefaultListModel();
        int i=0;
        for(String s:lst)
            listModel.addElement("[" + i++ + "] " + s);
        listModel.addElement("<<insert new here>>");
        nameList.setModel(listModel);
        if (index>=0 && index<=listModel.size()){
            nameList.setSelectedIndex(index);
        } else nameList.setSelectedIndex(0);
    }
    
    
    
    
    public String getSelectedName(){
        if (nameList.getModel().getSize()!=0 && nameList.getSelectedIndex()==-1)
            nameList.setSelectedIndex(0);
        return getName((String) nameList.getSelectedValue());
    }
    
    
    
    protected void editField(){
        int index = nameList.getSelectedIndex();
        boolean edit = index!=-1 && index != lst.size();
        String toShow = edit? getSelectedName() : "";
        String name = JOptionPane.showInputDialog(ADD_NEW_NAME,toShow);
        if (name == null || name.isEmpty()) return;
        if (edit)
            lst.set(index, name);
        else lst.add(name);
        updateFields();
    }
    
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        nameList = new javax.swing.JList();
        addName = new javax.swing.JButton();
        up1But = new javax.swing.JButton();
        down1But = new javax.swing.JButton();
        label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        addName1 = new javax.swing.JButton();

        nameList.setFont(new java.awt.Font("Verdana", 1, 12));
        nameList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Olá" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        nameList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        nameList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameListMouseClicked(evt);
            }
        });
        nameList.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nameListKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameListKeyTyped(evt);
            }
        });
        jScrollPane4.setViewportView(nameList);

        addName.setText("  add  ");
        addName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNameActionPerformed(evt);
            }
        });

        up1But.setText("   up  ");
        up1But.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                up1ButActionPerformed(evt);
            }
        });

        down1But.setText("down");
        down1But.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                down1ButActionPerformed(evt);
            }
        });

        label.setFont(new java.awt.Font("Verdana", 1, 14));
        label.setText("jLabel1");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel1.setText("Up/Down to navigate    Enter to edit (or add)");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel2.setText("Delete to remove          Shift+Up/Shift+Down to move");

        label1.setFont(new java.awt.Font("Verdana", 1, 14));
        label1.setText("Keyboard:");

        addName1.setText("delete");
        addName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addName1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addName1)
                            .addComponent(addName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(up1But)
                            .addComponent(down1But))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(down1But)
                            .addComponent(addName1)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(up1But)
                        .addComponent(addName)))
                .addGap(6, 6, 6)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNameActionPerformed
        String name = JOptionPane.showInputDialog(ADD_NEW_NAME);
        if (name == null) return;
        int index = nameList.getSelectedIndex()+1;
        if (index >=0 && index < lst.size())
            lst.add(index,name);
        else lst.add(name);
        updateFields();
  
}//GEN-LAST:event_addNameActionPerformed

    private void nameListKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameListKeyTyped
        
    }//GEN-LAST:event_nameListKeyTyped

    private void nameListKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameListKeyPressed
        int index = nameList.getSelectedIndex();
        switch (evt.getKeyCode()){
            case KeyEvent.VK_DELETE:
                if (index >=0 && index < lst.size()){
                    lst.remove(index);
                    updateFields();
                }
                break;
            case KeyEvent.VK_ENTER:
                //((DefaultListModel)nameList.getModel()).remove(index);
                editField();
                break;
            case KeyEvent.VK_UP:
                if (evt.isShiftDown()){
                    up1ButActionPerformed(null);
                    if (index<lst.size()) nameList.setSelectedIndex(index);
                }
                break;
            case KeyEvent.VK_DOWN:
                if (evt.isShiftDown()){
                    down1ButActionPerformed(null);
                    if (index>=0) nameList.setSelectedIndex(index);
                }
                break;
        }
    }//GEN-LAST:event_nameListKeyPressed

    private void nameListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameListMouseClicked
        if (evt.getClickCount() == 2){
            editField();
        }
    }//GEN-LAST:event_nameListMouseClicked

    private void up1ButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up1ButActionPerformed
        int index = nameList.getSelectedIndex();
        if (index >0 && index < lst.size()){
            // do the swap
            String tmp = lst.get(index-1);
            lst.set(index-1, lst.get(index));
            lst.set(index, tmp);
            updateFields();
            nameList.setSelectedIndex(index-1);
        }
    }//GEN-LAST:event_up1ButActionPerformed

    private void down1ButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down1ButActionPerformed
        int index = nameList.getSelectedIndex();
        if (index >= 0 && index < lst.size()-1){
            // do the swap
            String tmp = lst.get(index+1);
            lst.set(index+1, lst.get(index));
            lst.set(index, tmp);
            updateFields();
            nameList.setSelectedIndex(index+1);
        }
    }//GEN-LAST:event_down1ButActionPerformed

    private void addName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addName1ActionPerformed
        int index = nameList.getSelectedIndex();
        if (index >=0 && index < lst.size()){
            lst.remove(index);
            updateFields();
        }
    }//GEN-LAST:event_addName1ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addName;
    private javax.swing.JButton addName1;
    private javax.swing.JButton down1But;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel label;
    private javax.swing.JLabel label1;
    private javax.swing.JList nameList;
    private javax.swing.JButton up1But;
    // End of variables declaration//GEN-END:variables
    
}
