/*
 * MassCenterPanel.java
 *
 * Created on 27 November 2008, 10:11
 */

package gui;

import image.ImageUtils;
import java.awt.Color;
import util.IColorTaker;


/**
 *
 * @author  Gil Costa
 */
public class ColorPanel extends javax.swing.JPanel implements IColorTaker{
    /** panel that shows the image */
    FramePanel framePanel;
    
    /** Creates new form MassCenterPanel */
    public ColorPanel() {
        initComponents();
        setAllEnabled(false);
    }
    
    //---------------------
    // ----- SETTERS -----
    //---------------------
    
    public void setAllEnabled(boolean enabled){
        this.setEnabled(enabled);
        cmCheck.setEnabled(enabled);
        if(enabled && cmCheck.isSelected())
            setFieldsEnabled(true);
        else setFieldsEnabled(false);
    }
    
    protected void setFieldsEnabled(boolean enabled){
        panel.setEnabled(enabled);
        rField.setEnabled(enabled);
        gField.setEnabled(enabled);
        bField.setEnabled(enabled);
        pickTogle.setEnabled(enabled);
        autoBut.setEnabled(enabled);
    }
    
    
    public void setFramePanel(FramePanel framePanel){
        this.framePanel = framePanel;
        reset();
        if (framePanel!=null)
            autoButActionPerformed(null);
    }
    
    
    protected void reset(){
        boolean enabled = framePanel!=null;
        setAllEnabled(enabled);
    }
    
    
    protected void update(){
        Color c = miniPanel.getBackground();
        int r = c.getRed();
        int g = c.getGreen();
        int b = c.getBlue();
        try{
            r = Integer.parseInt(rField.getText());
            g = Integer.parseInt(gField.getText());
            b = Integer.parseInt(bField.getText());
        }catch (NumberFormatException e){}
        r = ImageUtils.normalised(r);
        g = ImageUtils.normalised(g);
        b = ImageUtils.normalised(b);
        c = new Color(r,g,b);
        takeColor(c);
    }
    
    
    
    public void takeColor(Color c) {
        rField.setText(c.getRed()+"");
        gField.setText(c.getGreen()+"");
        bField.setText(c.getBlue()+"");
        miniPanel.setBackground(c);
        miniPanel.repaint();
    }
    
    
    public void pickSelected(boolean selected){
        pickTogle.setSelected(selected);
        pickTogleActionPerformed(null);
    }
    
    
    
    //-------------------
    // ---- GETTERS ----
    //-------------------
    
    public boolean isChecked(){
        return cmCheck.isSelected();
    }
    
    public Color getTransparentColor(){
        return miniPanel.getBackground();
    }
    
  
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        gField = new javax.swing.JTextField();
        rField = new javax.swing.JTextField();
        bField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        autoBut = new javax.swing.JButton();
        miniPanel = new javax.swing.JPanel();
        pickTogle = new javax.swing.JToggleButton();
        cmCheck = new javax.swing.JCheckBox();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("R");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("G");

        gField.setColumns(3);
        gField.setText("0");
        gField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gFieldActionPerformed(evt);
            }
        });
        gField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                gFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                gFieldFocusLost(evt);
            }
        });

        rField.setColumns(3);
        rField.setText("0");
        rField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rFieldActionPerformed(evt);
            }
        });
        rField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                rFieldFocusLost(evt);
            }
        });

        bField.setColumns(3);
        bField.setText("0");
        bField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFieldActionPerformed(evt);
            }
        });
        bField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                bFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                bFieldFocusLost(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("B");

        autoBut.setText("automatic");
        autoBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoButActionPerformed(evt);
            }
        });

        miniPanel.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout miniPanelLayout = new javax.swing.GroupLayout(miniPanel);
        miniPanel.setLayout(miniPanelLayout);
        miniPanelLayout.setHorizontalGroup(
            miniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );
        miniPanelLayout.setVerticalGroup(
            miniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        pickTogle.setText("pick");
        pickTogle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pickTogleActionPerformed(evt);
            }
        });
        pickTogle.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                pickTogleFocusLost(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pickTogle, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(autoBut)))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(miniPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rField)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gField)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addComponent(miniPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)))
                .addComponent(autoBut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pickTogle)
                .addContainerGap())
        );

        cmCheck.setSelected(true);
        cmCheck.setText("Transparent BackGround");
        cmCheck.setActionCommand("Transparent Background");
        cmCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmCheckActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmCheck, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(cmCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void gFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gFieldActionPerformed
        update();
        bField.requestFocus();
}//GEN-LAST:event_gFieldActionPerformed

    private void gFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_gFieldFocusGained
        gField.selectAll();
}//GEN-LAST:event_gFieldFocusGained

    private void gFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_gFieldFocusLost
        update();
}//GEN-LAST:event_gFieldFocusLost

    private void rFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rFieldActionPerformed
        update();
        gField.requestFocus();
}//GEN-LAST:event_rFieldActionPerformed

    private void rFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rFieldFocusGained
        rField.selectAll();
}//GEN-LAST:event_rFieldFocusGained

    private void rFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rFieldFocusLost
        update();
}//GEN-LAST:event_rFieldFocusLost

    private void cmCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmCheckActionPerformed
        boolean checked = cmCheck.isSelected();
        setFieldsEnabled(checked);
        if (!checked){

            framePanel.repaint();
        }
        else update();
    }//GEN-LAST:event_cmCheckActionPerformed

    private void bFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFieldActionPerformed
        update();
        requestFocus();
}//GEN-LAST:event_bFieldActionPerformed

    private void bFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bFieldFocusGained
        bField.selectAll();
}//GEN-LAST:event_bFieldFocusGained

    private void bFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bFieldFocusLost
        update();
}//GEN-LAST:event_bFieldFocusLost

    private void pickTogleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pickTogleActionPerformed
        framePanel.pickColor(pickTogle.isSelected());
    }//GEN-LAST:event_pickTogleActionPerformed

    private void autoButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoButActionPerformed
        if (framePanel==null || framePanel.getFrame()==null || framePanel.getFrame().getImage() == null)
            return;
        Color c = ImageUtils.borderPredominance(framePanel.getFrame().getImage());
        takeColor(c);
    }//GEN-LAST:event_autoButActionPerformed

    private void pickTogleFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pickTogleFocusLost
        pickTogle.setSelected(false);
        pickTogleActionPerformed(null);
    }//GEN-LAST:event_pickTogleFocusLost
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton autoBut;
    private javax.swing.JTextField bField;
    private javax.swing.JCheckBox cmCheck;
    private javax.swing.JTextField gField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel miniPanel;
    private javax.swing.JPanel panel;
    private javax.swing.JToggleButton pickTogle;
    private javax.swing.JTextField rField;
    // End of variables declaration//GEN-END:variables

    
}
