/*
 * OpenImgs.java
 *
 * Created on 19 October 2008, 17:17
 */

package gui;

import frames.Frame;
import frames.IFramesTaker;
import game.GameInvariants;
import image.ImageUtils;
import image.IFilter;
import image.TransparentMaker;
import java.awt.Color;

import java.awt.image.BufferedImage;
import util.IColorTaker;
import util.ICoordinatesTaker;
import util.IntPoint;

/**
 *
 * @author  Gil Costa
 */
public class OpenImgs extends javax.swing.JFrame implements ICoordinatesTaker, IColorTaker {
    
     /** frame panel */
	protected gui.FramePanel framePanel;
    protected IFramesTaker framesTaker;
    protected BufferedImage[] imgs;
    
    
    /** Creates new form OpenImgs */
    public OpenImgs(IFramesTaker collectionTaker, BufferedImage[] images) {
        this.framesTaker = collectionTaker;
        
        initComponents();
        initAdvancedComponents();
        
        framePanel.setFrame(new Frame(images[0],GameInvariants.FRAMES_VERSION));
        imgs = images;
        massCenterPanel.setFramePanel(framePanel);
        colorPanel.setFramePanel(framePanel);
    }
    
    
    public OpenImgs(IFramesTaker collectionTaker, BufferedImage image) {
        this.framesTaker = collectionTaker;
        
        initComponents();
        initAdvancedComponents();
        
        framePanel.setFrame(new Frame(image,GameInvariants.FRAMES_VERSION));
        stripPanel.setFramePanel(framePanel);
        stripPanel.setImage(image);
        stripPanel.requestFocus();
        imgs = new BufferedImage[1];
        imgs[0] = image;
        massCenterPanel.setFramePanel(framePanel);
        colorPanel.setFramePanel(framePanel);
    }
    
    
    
      protected void initAdvancedComponents(){
    	framePanel = new gui.FramePanel(scroller, this, colorPanel);

        framePanel.setBackground(new java.awt.Color(0, 102, 102));
        framePanel.setForeground(new java.awt.Color(255, 255, 255));
        scroller.setViewportView(framePanel);
        scroller.setWheelScrollingEnabled(false);
    }
    
    
    
    
    
    
	@Override
	public void takeCoordinates(int index, int x, int y){
		massCenterPanel.takeCoordinates(index, x,y);
	}
	
	@Override
	public void takeColor(Color c){
		
	}
    
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okBut = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        scroller = new gui.Scroller();
        massCenterPanel = new gui.HotSpotPanel();
        stripPanel = new gui.StripPanel();
        cancelBut = new javax.swing.JButton();
        colorPanel = new gui.ColorPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Opening images");
        setLocationByPlatform(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        okBut.setText("   Ok   ");
        okBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButActionPerformed(evt);
            }
        });

        jLabel5.setText("First Frame preview");

        massCenterPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        stripPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cancelBut.setText("Canccel");
        cancelBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButActionPerformed(evt);
            }
        });

        colorPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(okBut)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cancelBut))
                            .addComponent(colorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(massCenterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(stripPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scroller, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(107, 107, 107))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(stripPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(massCenterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(colorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(okBut)
                            .addComponent(cancelBut)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scroller, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO: here
        framesTaker.takeFrames(null);
    }//GEN-LAST:event_formWindowClosed

    private void okButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButActionPerformed
        IntPoint cm = framePanel.getFrame().getCM();
        Frame[] frames;
        BufferedImage[] finalImgs = imgs;
        // if split is enabled, generate strip images
        if (stripPanel.isEnabled() && stripPanel.isChecked())
            finalImgs = ImageUtils.split(imgs[0], stripPanel.getCols(), stripPanel.getRows());
       
        // add all images to frames, with the same mass center, but crop them
        // and make transparent if that option is on
        IFilter f = null;
        if (colorPanel.isChecked())
            f = new TransparentMaker(colorPanel.getTransparentColor());
        frames = new Frame[finalImgs.length];
        for (int i=0; i<finalImgs.length; i++){
            if (f!=null) f.applyTo(finalImgs[i]);
            frames[i] = new Frame(finalImgs[i],cm.clone(), GameInvariants.FRAMES_VERSION);                
            if (!frames[i].cropFrame())
                frames[i] = null;
        }
        framesTaker.takeFrames(frames);
        this.dispose();
    }//GEN-LAST:event_okButActionPerformed

    private void cancelButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButActionPerformed
        framesTaker.takeFrames(null);
        dispose();
}//GEN-LAST:event_cancelButActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBut;
    private gui.ColorPanel colorPanel;
    private javax.swing.JLabel jLabel5;
    private gui.HotSpotPanel massCenterPanel;
    private javax.swing.JButton okBut;
    private gui.Scroller scroller;
    private gui.StripPanel stripPanel;
    // End of variables declaration//GEN-END:variables
    
}
